language: java

jdk: oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

before_script:
 - git config user.name "$COMMIT_AUTHOR_NAME"
 - git config user.email "$COMMIT_AUTHOR_EMAIL"
 - export COMMIT_MESSAGE=`git log -1 --oneline`

script:
  - ./mvnw clean install
  - ./push-gh.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)